### ISSUE TITLE
Login Token

### ISSUE THREAD

**Issue by triniwiz** [otalk/stanza.io#81]
Is there any way to get a some sort of token if a user is logged in so they won't need to retype their details each time they need to use the app ???

oh i'm trying to use stanza.io for my ionic app also i use prosody for my xmpp server i know theres bosh but i want to use websockets

**Comment by legastero** [comment]
This isn't really a stanza.io specific issue, but it is a frequently encountered one.

So, first: if you need to work with arbitrary third-party servers (i.e. your app users can use their own server), then your only options are to either securely store the credentials or ask every time. There really isn't much else that can be done in this case no matter what library or platform you're using.

If the server supports `SCRAM-SHA-1` (and for Prosody also using `authentication = "internal_hashed
` so that the salt isn't new for every auth attempt), then you can get away with storing just the `clientKey` and `serverKey` data emitted in the `credentials:update` event. However, those are password-equivalents, so while you wouldn't be saving the user's plaintext password, someone with access to those could still log into the user's XMPP account.

Otherwise, you would need to create your own auth mechanism for your server. You could use the value of a cookie or an OAuth access token (or an OpenID-Conenct id token) as the password and abuse `PLAIN` authentication, or make a custom named SASL mechanism to do the same. I've done the OAuth method several times.

BOSH has an advantage in that you can do pre-binding for your users, and there are several tools for doing that already. WebSocket doesn't have that ability in quite the same way. The closest equivalent would be for the server to allow XEP-0198 session resumption before authentication, and have something pre-bind a session and provide the session resumption token. AFAIK, there are no existing tools for doing that sort of pre-binding using session resumption yet.

Again, this is a generic issue that requires a server-side solution that stanza.io won't be able to provide itself.

**Comment by triniwiz** [comment]
Thanks
