### ISSUE TITLE
node-xmpp

### ISSUE THREAD

**Issue by sonnyp** [otalk/stanza.io#82]
Hello @legastero 

stanza.io is great stuff! I wondered if you'd be interested in moving to node-xmpp-client and if there something I could do to help.

We added BOSH SASL restart support yesterday https://github.com/node-xmpp/node-xmpp-client/pull/91

**Comment by legastero** [comment]
At the moment, no. There are enough differences between the two that I don't see any gain in switching right now.

That said, I'll revisit the idea in the future. I already had to switch to using `ltx` to deal with browser inconsistencies, so I'd like to split out all of the JSON transformations into their own modules so that they can be used in the `node-xmpp` ecosystem, like `node-xmpp-component` :)

**Comment by sonnyp** [comment]
>  split out all of the JSON transformations into their own modules so that they can be used in the node-xmpp ecosystem, like node-xmpp-component :)

@legastero awesome, one of the thing I had though about!

**Comment by sonnyp** [comment]
@legastero could you explain what are the differences between the two that would prevent 
benefit from the switch?

**Comment by legastero** [comment]
From a quick skim through, I noticed at least:

- No `SCRAM-SHA-1

**Comment by sonnyp** [comment]
@legastero so I can start with SCRAM-SHA-1 support on node-xmpp-client :)
Thanks, let me know if there is anything else.

**Comment by legastero** [comment]
It would be worth looking into using https://www.npmjs.com/package/saslmechanisms in `node-xmpp-client` (this is what stanza uses). Then you'd be able to use https://www.npmjs.com/package/sasl-scram-sha-1, along with all of the currently supported mechs.

**Comment by sonnyp** [comment]
@legastero https://github.com/node-xmpp/node-xmpp/pull/309

This is WIP but I'd love to get early feedback from you and see if it looks good enough for stanza.io ?
