### ISSUE TITLE
How to keep long-lived chat room presence alive

### ISSUE THREAD

**Issue by metalaureate** [otalk/stanza.io#89]
This more of a "good practice" question in using stanza.io effectively. I am writing a chat room daemon that needs to hang out in active chat rooms. After 60 seconds of inactivity my XMPP server ends the BOSH connection for inactivity. What's the minimum I can send over the wire periodically to keep the connection alive? I've been sending joinRoom, which works, but that triggers a cascade of events like retrieval of message history. I'd be very grateful if you knew what to do here.

**Comment by legastero** [comment]
Some options here:

1. Send a `<presence/>` stanza every so often (`sendPresence()` instead of `joinRoom()`). That is the minimum size stanza you can have short of using stream management acks.
2. Use `client.enableKeepalive({ interval: 30 })` to make stanza send XEP-0199 pings (or SM acks if available) every 30sec.

However, for BOSH specifically, this is supposed to not be an issue. Stanza should be expiring and making new HTTP requests often enough for it to not be a problem (defaults to 30sec). Which server are you using?

**Comment by metalaureate** [comment]
I use prosody. I'll double check I am understanding what is going on correctly. Thank you very much for these ideas!

**Comment by metalaureate** [comment]
client.enableKeepalive({ interval: 30 }) seems to have fixed my problem. That and removing the superstitious cruft from my code resulting from my lack of clarity about how BOSH works. Thanks again for the help.

**Comment by metalaureate** [comment]
@legastero Would you be able to recommend a good way to detect if the connection has dropped? I know that is not meant to happen, but in dev, on my laptop, after it goes to sleep my stanza.io functions to rejoinRooms() seem to go through the motions, but the server as terminated the connection and I get no connection end or connection error events. Thanks!
